name: helenyung
favicon: null
layout_spectrum: 0.4325981580186635
typography_spectrum: 0.7595296881627291
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.8566980706527829
  lightness: 0.4981514420360327
  saturation: 0.7223567753098905
  rhythmicContrast: 0.6600660237018019
purpose: []
