analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.7223567753098905
  brandStrength: 1
  lightness: 0.4981514420360327
  brandColors:
    - '#B4B6B3'
    - '#4B0F0C'
    - '#44BCC5'
    - '#544B41'
    - '#78786D'
  rhythmicContrast: 0.6600660237018019
typography_spectrum: 0.5531915
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.99741
favicon: null
name: helenyung
