name: helenyung
favicon: null
layout_spectrum: 0.99741
typography_spectrum: 0.5531915
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#090806'
    - '#cec7ba'
    - '#58554e'
    - '#ac5750'
  brandStrength: 1
  lightness: 0.4981514420360327
  saturation: 0.7223567753098905
  rhythmicContrast: 0.6600660237018019
purpose: []
